Don't promote during weekend period AEST
OctopusDeploy/OctopusDeploy-EnthusiasticPromotions pull request #7
Opened 2020-11-23 04:24 UTC by Silcoish

Between 4pm Friday and 8am Monday AEST, we don't want to promote anymore releases to avoid a situation where something goes out to production and requires multiple people to be on deck while everyone is offline for their weekend.

2020-11-23 05:19 UTC, matt-richardson requested changes
Looking good. I think we can pull the logic out to a function and then we'll be able to do some nicer more targetd tests

2020-11-23 05:19 UTC, matt-richardson commented on enthusiastic-promoter.ps1
> +                    # Don't promote after 4pm Friday and 8am Monday morning
I'd suggest pulling this into a `Test-IsWeekend` function - that would be nice and testable.
You'd be able to skip the `return` then (as it'd become part of the `else if (Test-IsWeekend Get-CurrentDate) { ... }`)

2020-11-23 05:19 UTC, matt-richardson commented on enthusiastic-promotor.tests.ps1
> +  It 'should not promote during weekend period' {
If you pulled out the code into a `Test-IsWeekend` function, then you'd only need to test what the behaviour for `Get-PromotionCandidates` is when it returns false (as the other tests would test the `$true` case).
Then you could have some nice easy tests for over the weekend.

2020-11-23 05:19 UTC, matt-richardson commented on enthusiastic-promoter.ps1
> +                        Write-Host " - Bake time is complete but skipping promotion as we don't want to promote releases between 4pm Friday AEST and 8am Monday AEST."
Consider rewording this to emphasise the why, rather than the what

2020-11-24 01:24 UTC, Silcoish commented on enthusiastic-promoter.ps1
> +                    Write-Host " - Bake time is complete but we aren't going to promote it as it's between 4pm Friday AEST and 8am Monday AEST to avoid potential issues with rolling out to more custo
```suggestion
                    Write-Host " - Bake time is complete but we aren't going to promote the release as it's between 4pm Friday AEST and 8am Monday AEST. To avoid potential issues with rolling out to customers over the weekend when a large marjority of our team will be unavailable to assist with fixes, we'll wait until Monday."
```

Might be a bit better wording

2020-11-24 01:32 UTC, matt-richardson reviewed
Looking pretty good - a few suggestions

2020-11-24 01:32 UTC, matt-richardson commented on enthusiastic-promoter.ps1
> +                    Write-Host " - Bake time is complete but we aren't going to promote it as it's between 4pm Friday AEST and 8am Monday AEST to avoid potential issues with rolling out to more custo
```suggestion
                    Write-Host " - Bake time is complete but we aren't going to promote it as it's between 4pm Friday AEST and 8am Monday AEST. This helps us avoid potential issues with rolling out to lots of customers over the weekend when a large majority of our team is unavailable to assist if something goes wrong."
```

2020-11-24 01:32 UTC, matt-richardson commented on enthusiastic-promoter.ps1
> +                    return;
Dont need the return anymore
```suggestion
```

2020-11-24 01:32 UTC, matt-richardson commented on enthusiastic-promoter.ps1
> +                else {
```suggestion
                } else {
```

2020-11-24 01:32 UTC, matt-richardson commented on enthusiastic-promotor.tests.ps1
> +      [Int] $expectedResults
Consider making this a bool instead. Might be clearer than asserting on number of results

2020-11-24 01:42 UTC, matt-richardson approved these changes
Couple of tweaks then you're good to go

2020-11-24 01:42 UTC, matt-richardson commented on enthusiastic-promotor.tests.ps1
> +      [Int] $shouldPromote
```suggestion
      [boolean] $shouldPromote
```

2020-11-24 01:42 UTC, matt-richardson commented on enthusiastic-promotor.tests.ps1
> +    }
```suggestion
    ($result.Count -gt 0) | should -be $shouldPromote
```

2020-11-24 02:04 UTC, merged